package recommend;
// Generated Sep 10, 2015 5:08:34 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
import java.util.List;
import java.util.ListIterator;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="user")
public class User{

     @Id
     @Column(name="id")
     @GeneratedValue(strategy=GenerationType.IDENTITY)
     private int idUser;
     private int a1;
     private int a2;
     private int a3;
     private int a4;
     private int a5;
     private int a6;
     private int a7;
     private int a8;
     private int a9;
     private int a10;
     private int a11;
     private int a12;
     private int a13;
     private int a14;
     private int a15;
     private int a16;
     private int a17;
     private int a18;
     private int a19;
     private int a20;
     private int a21;
     private int a22;
     private int a23;
     private int a24;
     private int a25;
     private int a26;
     private int a27;
     private int a28;
     private int a29;
     private int a30;
     private int a31;
     private int a32;
     private int a33;
     private int a34;
     private int a35;
     private int a36;
     private int a37;
     private int a38;
     private int a39;
     private int a40;
     private int a41;
     private int a42;
     private int a43;
     private int a44;
     private double extr;
     private double agr;
     private double cons;
     private double neur;
     private double opn;
     @Column(columnDefinition="varchar(30)")
     private String username;
     @Column(columnDefinition="varchar(30)")
     private String password;

    public User() {
    }

    public User(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23, int a24, int a25, int a26, int a27, int a28, int a29, int a30, int a31, int a32, int a33, int a34, int a35, int a36, int a37, int a38, int a39, int a40, int a41, int a42, int a43, int a44, double extr, double agr, double cons, double neur, double opn) {
       this.a1 = a1;
       this.a2 = a2;
       this.a3 = a3;
       this.a4 = a4;
       this.a5 = a5;
       this.a6 = a6;
       this.a7 = a7;
       this.a8 = a8;
       this.a9 = a9;
       this.a10 = a10;
       this.a11 = a11;
       this.a12 = a12;
       this.a13 = a13;
       this.a14 = a14;
       this.a15 = a15;
       this.a16 = a16;
       this.a17 = a17;
       this.a18 = a18;
       this.a19 = a19;
       this.a20 = a20;
       this.a21 = a21;
       this.a22 = a22;
       this.a23 = a23;
       this.a24 = a24;
       this.a25 = a25;
       this.a26 = a26;
       this.a27 = a27;
       this.a28 = a28;
       this.a29 = a29;
       this.a30 = a30;
       this.a31 = a31;
       this.a32 = a32;
       this.a33 = a33;
       this.a34 = a34;
       this.a35 = a35;
       this.a36 = a36;
       this.a37 = a37;
       this.a38 = a38;
       this.a39 = a39;
       this.a40 = a40;
       this.a41 = a41;
       this.a42 = a42;
       this.a43 = a43;
       this.a44 = a44;
       this.extr = extr;
       this.agr = agr;
       this.cons = cons;
       this.neur = neur;
       this.opn = opn;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public int getA1() {
        return this.a1;
    }
    
    public void setA1(int a1) {
        this.a1 = a1;
    }
    public int getA2() {
        return this.a2;
    }
    
    public void setA2(int a2) {
        this.a2 = a2;
    }
    public int getA3() {
        return this.a3;
    }
    
    public void setA3(int a3) {
        this.a3 = a3;
    }
    public int getA4() {
        return this.a4;
    }
    
    public void setA4(int a4) {
        this.a4 = a4;
    }
    public int getA5() {
        return this.a5;
    }
    
    public void setA5(int a5) {
        this.a5 = a5;
    }
    public int getA6() {
        return this.a6;
    }
    
    public void setA6(int a6) {
        this.a6 = a6;
    }
    public int getA7() {
        return this.a7;
    }
    
    public void setA7(int a7) {
        this.a7 = a7;
    }
    public int getA8() {
        return this.a8;
    }
    
    public void setA8(int a8) {
        this.a8 = a8;
    }
    public int getA9() {
        return this.a9;
    }
    
    public void setA9(int a9) {
        this.a9 = a9;
    }
    public int getA10() {
        return this.a10;
    }
    
    public void setA10(int a10) {
        this.a10 = a10;
    }
    public int getA11() {
        return this.a11;
    }
    
    public void setA11(int a11) {
        this.a11 = a11;
    }
    public int getA12() {
        return this.a12;
    }
    
    public void setA12(int a12) {
        this.a12 = a12;
    }
    public int getA13() {
        return this.a13;
    }
    
    public void setA13(int a13) {
        this.a13 = a13;
    }
    public int getA14() {
        return this.a14;
    }
    
    public void setA14(int a14) {
        this.a14 = a14;
    }
    public int getA15() {
        return this.a15;
    }
    
    public void setA15(int a15) {
        this.a15 = a15;
    }
    public int getA16() {
        return this.a16;
    }
    
    public void setA16(int a16) {
        this.a16 = a16;
    }
    public int getA17() {
        return this.a17;
    }
    
    public void setA17(int a17) {
        this.a17 = a17;
    }
    public int getA18() {
        return this.a18;
    }
    
    public void setA18(int a18) {
        this.a18 = a18;
    }
    public int getA19() {
        return this.a19;
    }
    
    public void setA19(int a19) {
        this.a19 = a19;
    }
    public int getA20() {
        return this.a20;
    }
    
    public void setA20(int a20) {
        this.a20 = a20;
    }
    public int getA21() {
        return this.a21;
    }
    
    public void setA21(int a21) {
        this.a21 = a21;
    }
    public int getA22() {
        return this.a22;
    }
    
    public void setA22(int a22) {
        this.a22 = a22;
    }
    public int getA23() {
        return this.a23;
    }
    
    public void setA23(int a23) {
        this.a23 = a23;
    }
    public int getA24() {
        return this.a24;
    }
    
    public void setA24(int a24) {
        this.a24 = a24;
    }
    public int getA25() {
        return this.a25;
    }
    
    public void setA25(int a25) {
        this.a25 = a25;
    }
    public int getA26() {
        return this.a26;
    }
    
    public void setA26(int a26) {
        this.a26 = a26;
    }
    public int getA27() {
        return this.a27;
    }
    
    public void setA27(int a27) {
        this.a27 = a27;
    }
    public int getA28() {
        return this.a28;
    }
    
    public void setA28(int a28) {
        this.a28 = a28;
    }
    public int getA29() {
        return this.a29;
    }
    
    public void setA29(int a29) {
        this.a29 = a29;
    }
    public int getA30() {
        return this.a30;
    }
    
    public void setA30(int a30) {
        this.a30 = a30;
    }
    public int getA31() {
        return this.a31;
    }
    
    public void setA31(int a31) {
        this.a31 = a31;
    }
    public int getA32() {
        return this.a32;
    }
    
    public void setA32(int a32) {
        this.a32 = a32;
    }
    public int getA33() {
        return this.a33;
    }
    
    public void setA33(int a33) {
        this.a33 = a33;
    }
    public int getA34() {
        return this.a34;
    }
    
    public void setA34(int a34) {
        this.a34 = a34;
    }
    public int getA35() {
        return this.a35;
    }
    
    public void setA35(int a35) {
        this.a35 = a35;
    }
    public int getA36() {
        return this.a36;
    }
    
    public void setA36(int a36) {
        this.a36 = a36;
    }
    public int getA37() {
        return this.a37;
    }
    
    public void setA37(int a37) {
        this.a37 = a37;
    }
    public int getA38() {
        return this.a38;
    }
    
    public void setA38(int a38) {
        this.a38 = a38;
    }
    public int getA39() {
        return this.a39;
    }
    
    public void setA39(int a39) {
        this.a39 = a39;
    }
    public int getA40() {
        return this.a40;
    }
    
    public void setA40(int a40) {
        this.a40 = a40;
    }
    public int getA41() {
        return this.a41;
    }
    
    public void setA41(int a41) {
        this.a41 = a41;
    }
    public int getA42() {
        return this.a42;
    }
    
    public void setA42(int a42) {
        this.a42 = a42;
    }
    public int getA43() {
        return this.a43;
    }
    
    public void setA43(int a43) {
        this.a43 = a43;
    }
    public int getA44() {
        return this.a44;
    }
    
    public void setA44(int a44) {
        this.a44 = a44;
    }
    
    public double getExtr() {
        return this.extr;
    }
    
    public void setExtr(double extr) {
        this.extr =  extr;
    }
    
    public double getAgr() {
        return this.agr;
    }
    
    public void setAgr(double agr) {
        this.agr = agr;
    }
    
    public double getCons() {
        return this.cons;
    }
    
    public void setCons(double cons) {
        this.cons = cons;
    }
    public double getNeur() {
        return this.neur;
    }
    
    public void setNeur(double neur) {
        this.neur = neur;
    }
    public double getOpn() {
        return this.opn;
    }
    
    public void setOpn(double opn) {
        this.opn = opn;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public User(List<QuestionAnswer> answers) {
       ListIterator<QuestionAnswer> it = answers.listIterator();
       this.a1 = it.next().getValue();
       this.a2 = it.next().getValue();
       this.a3 = it.next().getValue();

    }

    public void flushValues(){     
        this.a1 = 0;
       this.a2 = 0;
       this.a3 = 0;
       this.a4 = 0;
       this.a5 = 0;
       this.a6 = 0;
       this.a7 = 0;
       this.a8 = 0;
       this.a9 = 0;
       this.a10 = 0;
       this.a11 = 0;
       this.a12 = 0;
       this.a13 = 0;
       this.a14 = 0;
       this.a15 = 0;
       this.a16 = 0;
       this.a17 = 0;
       this.a18 = 0;
       this.a19 = 0;
       this.a20 = 0;
       this.a21 = 0;
       this.a22 = 0;
       this.a23 = 0;
       this.a24 = 0;
       this.a25 = 0;
       this.a26 = 0;
       this.a27 = 0;
       this.a28 = 0;
       this.a29 = 0;
       this.a30 = 0;
       this.a31 = 0;
       this.a32 = 0;
       this.a33 = 0;
       this.a34 = 0;
       this.a35 = 0;
       this.a36 = 0;
       this.a37 = 0;
       this.a38 = 0;
       this.a39 = 0;
       this.a40 = 0;
       this.a41 = 0;
       this.a42 = 0;
       this.a43 = 0;
       this.a44 = 0;       
       this.extr = 0.0;
       this.agr = 0.0;
       this.cons = 0.0;
       this.neur = 0.0;
       this.opn = 0.0;
    }

    public void big5Scoring() {
        // Extraversion
        this.extr = (this.a1 + (6 - this.a6) + this.a11 + this.a16 + (6 - this.a21) + this.a26 + (6 - this.a31)+ this.a36)/8;
        //Agreeableness
        this.agr = ((6 - this.a2) + this.a7 + (6 - this.a12) + this.a17 + this.a22 + (6 - this.a27) + this.a32 + (6 - this.a37) + this.a42)/9;
        //Conscientiousness
        this.cons = (this.a3 + (6 - this.a8) + this.a13 + (6 - this.a18) + (6 - this.a23) + this.a28 + this.a33 + this.a38 + (6-this.a43))/9;
        //Neuroticism
        this.neur = (this.a4 + (6 - this.a9) + this.a14 + this.a19 + (6 - this.a24) + this.a29 + (6 - this.a34) + this.a39)/8;
        //Opennes
        this.opn = (this.a5 + this.a10 + this.a15 + this.a20 + this.a25 + this.a30 + (6 - this.a35) + this.a40 + (6 - this.a41) + this.a44)/10;
    }


}


