// Generated Sep 10, 2015 5:08:34 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
import java.util.List;
import java.util.ListIterator;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="h4lvd")
public class HarvardDictionary{
  @Id
  @Column(columnDefinition="varchar(19)")
  private String Entry;
  @Column(columnDefinition="varchar(30)")
  private String EntryEs;
  @Column(columnDefinition="varchar(30)")
  private String EntryFr;
  @Column(columnDefinition="varchar(30)")
  private String EntryAr;
  @Column(columnDefinition="varchar(5)")
  private String Source;
  private int Positiv;
  private int Negativ;
  private int Pstv;
  private int Affil;
  private int Ngtv;
  private int Hostile;
  private int Strong;
  private int Pow1;
  private int Weak;
  private int Submit;
  private int Active;
  private int Passive;
  private int Pleasur;
  private int Pain;
  private int Feel;
  private int Arousal;
  private int EMOT;
  private int Virtue;
  private int Vice;
  private int Ovrst;
  private int Undrst;
  private int Academ;
  private int Doctrin;
  private int Econat;
  private int Exch;
  private int ECON1;
  private int Exprsv;
  private int Legal;
  private int Milit;
  private int Polit;
  private int POLIT1;
  private int Relig;
  private int Role;
  private int COLL;
  private int Work1;
  private int Ritual;
  private int SocRel;
  private int Race;
  private int Kin;
  private int MALE;
  private int Female;
  private int Nonadlt;
  private int HU;
  private int ANI;
  private int PLACE;
  private int Social;
  private int Region;
  private int Route;
  private int Aquatic;
  private int Land;
  private int Sky;
  private int Object1;
  private int Tool;
  private int Food;
  private int Vehicle;
  private int BldgPt;
  private int ComnObj;
  private int NatObj;
  private int BodyPt;
  private int ComForm;
  private int COM;
  private int Say;
  private int Need;
  private int Goal;
  private int Try;
  private int Means;
  private int Persist;
  private int Complet;
  private int Fail;
  private int NatrPro;
  private int Begin1;
  private int Vary;
  private int Increas;
  private int Decreas;
  private int Finish;
  private int Stay;
  private int Rise;
  private int Exert;
  private int Fetch1;
  private int Travel;
  private int Fall;
  private int Think;
  private int Know;
  private int Causal;
  private int Ought;
  private int Perceiv;
  private int Compare;
  private int Eval;
  private int EVAL1;
  private int Solve;
  private int Absat;
  private int ABS1;
  private int Quality;
  private int Quan;
  private int NUMB;
  private int ORD1;
  private int CARD;
  private int FREQ;
  private int DIST;
  private int Timeat;
  private int TIME1;
  private int Space1;
  private int POS;
  private int DIM;
  private int Rel;
  private int COLOR;
  private int Self;
  private int Our;
  private int You;
  private int Name;
  private int Yes;
  private int No1;
  private int Negate;
  private int Intrj;
  private int IAV;
  private int DAV;
  private int SV;
  private int IPadj;
  private int IndAdj;
  private int PowGain;
  private int PowLoss;
  private int PowEnds;
  private int PowAren;
  private int PowCon;
  private int PowCoop;
  private int PowAuPt;
  private int PowPt;
  private int PowDoct;
  private int PowAuth;
  private int PowOth;
  private int PowTot;
  private int RcEthic;
  private int RcRelig;
  private int RcGain;
  private int RcLoss;
  private int RcEnds;
  private int RcTot;
  private int RspGain;
  private int RspLoss;
  private int RspOth;
  private int RspTot;
  private int AffGain;
  private int AffLoss;
  private int AffPt;
  private int AffOth;
  private int AffTot;
  private int WltPt;
  private int WltTran;
  private int WltOth;
  private int WltTot;
  private int WlbGain;
  private int WlbLoss;
  private int WlbPhys;
  private int WlbPsyc;
  private int WlbPt;
  private int WlbTot;
  private int EnlGain;
  private int EnlLoss;
  private int EnlEnds;
  private int EnlPt;
  private int EnlOth;
  private int EnlTot;
  private int SklAsth;
  private int SklPt;
  private int SklOth;
  private int SklTot;
  private int TrnGain;
  private int TrnLoss;
  private int TranLw;
  private int MeansLw;
  private int EndsLw;
  private int ArenaLw;
  private int PtLw;
  private int Nation;
  private int Anomie;
  private int NegAff;
  private int PosAff;
  private int SureLw;
  private int If1;
  private int NotLw;
  private int TimeSpc;
  private int FormLw;
  @Column(columnDefinition="varchar(40)")
  private String Othtags;
  @Column(columnDefinition="varchar(190)")
  private String Defined;

  public HarvardDictionary() {

  }

  public String getEntry() {
    return Entry;
  }

  public void setEntry(String Entry) {
    this.Entry = Entry;
  }

  public String getEntryEs() {
    return EntryEs;
  }

  public void setEntryEs(String EntryEs) {
    this.EntryEs = EntryEs;
  }

  public String getEntryFr() {
    return EntryFr;
  }

  public void setEntryFr(String EntryFr) {
    this.EntryFr = EntryFr;
  }

  public String getEntryAr() {
    return EntryAr;
  }

  public void setEntryAr(String EntryAr) {
    this.EntryAr = EntryAr;
  }

  public String getSource() {
    return Source;
  }

  public void setSource(String Source) {
    this.Source = Source;
  }

  public int getPositiv() {
    return Positiv;
  }

  public void setPositiv(int Positiv) {
    this.Positiv = Positiv;
  }

  public int getNegativ() {
    return Negativ;
  }

  public void setNegativ(int Negativ) {
    this.Negativ = Negativ;
  }

  public int getPstv() {
    return Pstv;
  }

  public void setPstv(int Pstv) {
    this.Pstv = Pstv;
  }

  public int getAffil() {
    return Affil;
  }

  public void setAffil(int Affil) {
    this.Affil = Affil;
  }

  public int getNgtv() {
    return Ngtv;
  }

  public void setNgtv(int Ngtv) {
    this.Ngtv = Ngtv;
  }

  public int getHostile() {
    return Hostile;
  }

  public void setHostile(int Hostile) {
    this.Hostile = Hostile;
  }

  public int getStrong() {
    return Strong;
  }

  public void setStrong(int Strong) {
    this.Strong = Strong;
  }

  public int getPow1() {
    return Pow1;
  }

  public void setPow1(int Pow1) {
    this.Pow1 = Pow1;
  }

  public int getWeak() {
    return Weak;
  }

  public void setWeak(int Weak) {
    this.Weak = Weak;
  }

  public int getSubmit() {
    return Submit;
  }

  public void setSubmit(int Submit) {
    this.Submit = Submit;
  }

  public int getActive() {
    return Active;
  }

  public void setActive(int Active) {
    this.Active = Active;
  }

  public int getPassive() {
    return Passive;
  }

  public void setPassive(int Passive) {
    this.Passive = Passive;
  }

  public int getPleasur() {
    return Pleasur;
  }

  public void setPleasur(int Pleasur) {
    this.Pleasur = Pleasur;
  }

  public int getPain() {
    return Pain;
  }

  public void setPain(int Pain) {
    this.Pain = Pain;
  }

  public int getFeel() {
    return Feel;
  }

  public void setFeel(int Feel) {
    this.Feel = Feel;
  }

  public int getArousal() {
    return Arousal;
  }

  public void setArousal(int Arousal) {
    this.Arousal = Arousal;
  }

  public int getEMOT() {
    return EMOT;
  }

  public void setEMOT(int EMOT) {
    this.EMOT = EMOT;
  }

  public int getVirtue() {
    return Virtue;
  }

  public void setVirtue(int Virtue) {
    this.Virtue = Virtue;
  }

  public int getVice() {
    return Vice;
  }

  public void setVice(int Vice) {
    this.Vice = Vice;
  }

  public int getOvrst() {
    return Ovrst;
  }

  public void setOvrst(int Ovrst) {
    this.Ovrst = Ovrst;
  }

  public int getUndrst() {
    return Undrst;
  }

  public void setUndrst(int Undrst) {
    this.Undrst = Undrst;
  }

  public int getAcadem() {
    return Academ;
  }

  public void setAcadem(int Academ) {
    this.Academ = Academ;
  }

  public int getDoctrin() {
    return Doctrin;
  }

  public void setDoctrin(int Doctrin) {
    this.Doctrin = Doctrin;
  }

  public int getEconat() {
    return Econat;
  }

  public void setEconat(int Econat) {
    this.Econat = Econat;
  }

  public int getExch() {
    return Exch;
  }

  public void setExch(int Exch) {
    this.Exch = Exch;
  }

  public int getECON1() {
    return ECON1;
  }

  public void setECON1(int ECON1) {
    this.ECON1 = ECON1;
  }

  public int getExprsv() {
    return Exprsv;
  }

  public void setExprsv(int Exprsv) {
    this.Exprsv = Exprsv;
  }

  public int getLegal() {
    return Legal;
  }

  public void setLegal(int Legal) {
    this.Legal = Legal;
  }

  public int getMilit() {
    return Milit;
  }

  public void setMilit(int Milit) {
    this.Milit = Milit;
  }

  public int getPolit() {
    return Polit;
  }

  public void setPolit(int Polit) {
    this.Polit = Polit;
  }

  public int getPOLIT1() {
    return POLIT1;
  }

  public void setPOLIT1(int POLIT1) {
    this.POLIT1 = POLIT1;
  }

  public int getRelig() {
    return Relig;
  }

  public void setRelig(int Relig) {
    this.Relig = Relig;
  }

  public int getRole() {
    return Role;
  }

  public void setRole(int Role) {
    this.Role = Role;
  }

  public int getCOLL() {
    return COLL;
  }

  public void setCOLL(int COLL) {
    this.COLL = COLL;
  }

  public int getWork1() {
    return Work1;
  }

  public void setWork1(int Work1) {
    this.Work1 = Work1;
  }

  public int getRitual() {
    return Ritual;
  }

  public void setRitual(int Ritual) {
    this.Ritual = Ritual;
  }

  public int getSocRel() {
    return SocRel;
  }

  public void setSocRel(int SocRel) {
    this.SocRel = SocRel;
  }

  public int getRace() {
    return Race;
  }

  public void setRace(int Race) {
    this.Race = Race;
  }

  public int getKin() {
    return Kin;
  }

  public void setKin(int Kin) {
    this.Kin = Kin;
  }

  public int getMALE() {
    return MALE;
  }

  public void setMALE(int MALE) {
    this.MALE = MALE;
  }

  public int getFemale() {
    return Female;
  }

  public void setFemale(int Female) {
    this.Female = Female;
  }

  public int getNonadlt() {
    return Nonadlt;
  }

  public void setNonadlt(int Nonadlt) {
    this.Nonadlt = Nonadlt;
  }

  public int getHU() {
    return HU;
  }

  public void setHU(int HU) {
    this.HU = HU;
  }

  public int getANI() {
    return ANI;
  }

  public void setANI(int ANI) {
    this.ANI = ANI;
  }

  public int getPLACE() {
    return PLACE;
  }

  public void setPLACE(int PLACE) {
    this.PLACE = PLACE;
  }

  public int getSocial() {
    return Social;
  }

  public void setSocial(int Social) {
    this.Social = Social;
  }

  public int getRegion() {
    return Region;
  }

  public void setRegion(int Region) {
    this.Region = Region;
  }

  public int getRoute() {
    return Route;
  }

  public void setRoute(int Route) {
    this.Route = Route;
  }

  public int getAquatic() {
    return Aquatic;
  }

  public void setAquatic(int Aquatic) {
    this.Aquatic = Aquatic;
  }

  public int getLand() {
    return Land;
  }

  public void setLand(int Land) {
    this.Land = Land;
  }

  public int getSky() {
    return Sky;
  }

  public void setSky(int Sky) {
    this.Sky = Sky;
  }

  public int getObject1() {
    return Object1;
  }

  public void setObject1(int Object1) {
    this.Object1 = Object1;
  }

  public int getTool() {
    return Tool;
  }

  public void setTool(int Tool) {
    this.Tool = Tool;
  }

  public int getFood() {
    return Food;
  }

  public void setFood(int Food) {
    this.Food = Food;
  }

  public int getVehicle() {
    return Vehicle;
  }

  public void setVehicle(int Vehicle) {
    this.Vehicle = Vehicle;
  }

  public int getBldgPt() {
    return BldgPt;
  }

  public void setBldgPt(int BldgPt) {
    this.BldgPt = BldgPt;
  }

  public int getComnObj() {
    return ComnObj;
  }

  public void setComnObj(int ComnObj) {
    this.ComnObj = ComnObj;
  }

  public int getNatObj() {
    return NatObj;
  }

  public void setNatObj(int NatObj) {
    this.NatObj = NatObj;
  }

  public int getBodyPt() {
    return BodyPt;
  }

  public void setBodyPt(int BodyPt) {
    this.BodyPt = BodyPt;
  }

  public int getComForm() {
    return ComForm;
  }

  public void setComForm(int ComForm) {
    this.ComForm = ComForm;
  }

  public int getCOM() {
    return COM;
  }

  public void setCOM(int COM) {
    this.COM = COM;
  }

  public int getSay() {
    return Say;
  }

  public void setSay(int Say) {
    this.Say = Say;
  }

  public int getNeed() {
    return Need;
  }

  public void setNeed(int Need) {
    this.Need = Need;
  }

  public int getGoal() {
    return Goal;
  }

  public void setGoal(int Goal) {
    this.Goal = Goal;
  }

  public int getTry() {
    return Try;
  }

  public void setTry(int Try) {
    this.Try = Try;
  }

  public int getMeans() {
    return Means;
  }

  public void setMeans(int Means) {
    this.Means = Means;
  }

  public int getPersist() {
    return Persist;
  }

  public void setPersist(int Persist) {
    this.Persist = Persist;
  }

  public int getComplet() {
    return Complet;
  }

  public void setComplet(int Complet) {
    this.Complet = Complet;
  }

  public int getFail() {
    return Fail;
  }

  public void setFail(int Fail) {
    this.Fail = Fail;
  }

  public int getNatrPro() {
    return NatrPro;
  }

  public void setNatrPro(int NatrPro) {
    this.NatrPro = NatrPro;
  }

  public int getBegin1() {
    return Begin1;
  }

  public void setBegin1(int Begin1) {
    this.Begin1 = Begin1;
  }

  public int getVary() {
    return Vary;
  }

  public void setVary(int Vary) {
    this.Vary = Vary;
  }

  public int getIncreas() {
    return Increas;
  }

  public void setIncreas(int Increas) {
    this.Increas = Increas;
  }

  public int getDecreas() {
    return Decreas;
  }

  public void setDecreas(int Decreas) {
    this.Decreas = Decreas;
  }

  public int getFinish() {
    return Finish;
  }

  public void setFinish(int Finish) {
    this.Finish = Finish;
  }

  public int getStay() {
    return Stay;
  }

  public void setStay(int Stay) {
    this.Stay = Stay;
  }

  public int getRise() {
    return Rise;
  }

  public void setRise(int Rise) {
    this.Rise = Rise;
  }

  public int getExert() {
    return Exert;
  }

  public void setExert(int Exert) {
    this.Exert = Exert;
  }

  public int getFetch1() {
    return Fetch1;
  }

  public void setFetch1(int Fetch1) {
    this.Fetch1 = Fetch1;
  }

  public int getTravel() {
    return Travel;
  }

  public void setTravel(int Travel) {
    this.Travel = Travel;
  }

  public int getFall() {
    return Fall;
  }

  public void setFall(int Fall) {
    this.Fall = Fall;
  }

  public int getThink() {
    return Think;
  }

  public void setThink(int Think) {
    this.Think = Think;
  }

  public int getKnow() {
    return Know;
  }

  public void setKnow(int Know) {
    this.Know = Know;
  }

  public int getCausal() {
    return Causal;
  }

  public void setCausal(int Causal) {
    this.Causal = Causal;
  }

  public int getOught() {
    return Ought;
  }

  public void setOught(int Ought) {
    this.Ought = Ought;
  }

  public int getPerceiv() {
    return Perceiv;
  }

  public void setPerceiv(int Perceiv) {
    this.Perceiv = Perceiv;
  }

  public int getCompare() {
    return Compare;
  }

  public void setCompare(int Compare) {
    this.Compare = Compare;
  }

  public int getEval() {
    return Eval;
  }

  public void setEval(int Eval) {
    this.Eval = Eval;
  }

  public int getEVAL1() {
    return EVAL1;
  }

  public void setEVAL1(int EVAL1) {
    this.EVAL1 = EVAL1;
  }

  public int getSolve() {
    return Solve;
  }

  public void setSolve(int Solve) {
    this.Solve = Solve;
  }

  public int getAbsat() {
    return Absat;
  }

  public void setAbsat(int Absat) {
    this.Absat = Absat;
  }

  public int getABS1() {
    return ABS1;
  }

  public void setABS1(int ABS1) {
    this.ABS1 = ABS1;
  }

  public int getQuality() {
    return Quality;
  }

  public void setQuality(int Quality) {
    this.Quality = Quality;
  }

  public int getQuan() {
    return Quan;
  }

  public void setQuan(int Quan) {
    this.Quan = Quan;
  }

  public int getNUMB() {
    return NUMB;
  }

  public void setNUMB(int NUMB) {
    this.NUMB = NUMB;
  }

  public int getORD1() {
    return ORD1;
  }

  public void setORD1(int ORD1) {
    this.ORD1 = ORD1;
  }

  public int getCARD() {
    return CARD;
  }

  public void setCARD(int CARD) {
    this.CARD = CARD;
  }

  public int getFREQ() {
    return FREQ;
  }

  public void setFREQ(int FREQ) {
    this.FREQ = FREQ;
  }

  public int getDIST() {
    return DIST;
  }

  public void setDIST(int DIST) {
    this.DIST = DIST;
  }

  public int getTimeat() {
    return Timeat;
  }

  public void setTimeat(int Timeat) {
    this.Timeat = Timeat;
  }

  public int getTIME1() {
    return TIME1;
  }

  public void setTIME1(int TIME1) {
    this.TIME1 = TIME1;
  }

  public int getSpace1() {
    return Space1;
  }

  public void setSpace1(int Space1) {
    this.Space1 = Space1;
  }

  public int getPOS() {
    return POS;
  }

  public void setPOS(int POS) {
    this.POS = POS;
  }

  public int getDIM() {
    return DIM;
  }

  public void setDIM(int DIM) {
    this.DIM = DIM;
  }

  public int getRel() {
    return Rel;
  }

  public void setRel(int Rel) {
    this.Rel = Rel;
  }

  public int getCOLOR() {
    return COLOR;
  }

  public void setCOLOR(int COLOR) {
    this.COLOR = COLOR;
  }

  public int getSelf() {
    return Self;
  }

  public void setSelf(int Self) {
    this.Self = Self;
  }

  public int getOur() {
    return Our;
  }

  public void setOur(int Our) {
    this.Our = Our;
  }

  public int getYou() {
    return You;
  }

  public void setYou(int You) {
    this.You = You;
  }

  public int getName() {
    return Name;
  }

  public void setName(int Name) {
    this.Name = Name;
  }

  public int getYes() {
    return Yes;
  }

  public void setYes(int Yes) {
    this.Yes = Yes;
  }

  public int getNo1() {
    return No1;
  }

  public void setNo1(int No1) {
    this.No1 = No1;
  }

  public int getNegate() {
    return Negate;
  }

  public void setNegate(int Negate) {
    this.Negate = Negate;
  }

  public int getIntrj() {
    return Intrj;
  }

  public void setIntrj(int Intrj) {
    this.Intrj = Intrj;
  }

  public int getIAV() {
    return IAV;
  }

  public void setIAV(int IAV) {
    this.IAV = IAV;
  }

  public int getDAV() {
    return DAV;
  }

  public void setDAV(int DAV) {
    this.DAV = DAV;
  }

  public int getSV() {
    return SV;
  }

  public void setSV(int SV) {
    this.SV = SV;
  }

  public int getIPadj() {
    return IPadj;
  }

  public void setIPadj(int IPadj) {
    this.IPadj = IPadj;
  }

  public int getIndAdj() {
    return IndAdj;
  }

  public void setIndAdj(int IndAdj) {
    this.IndAdj = IndAdj;
  }

  public int getPowGain() {
    return PowGain;
  }

  public void setPowGain(int PowGain) {
    this.PowGain = PowGain;
  }

  public int getPowLoss() {
    return PowLoss;
  }

  public void setPowLoss(int PowLoss) {
    this.PowLoss = PowLoss;
  }

  public int getPowEnds() {
    return PowEnds;
  }

  public void setPowEnds(int PowEnds) {
    this.PowEnds = PowEnds;
  }

  public int getPowAren() {
    return PowAren;
  }

  public void setPowAren(int PowAren) {
    this.PowAren = PowAren;
  }

  public int getPowCon() {
    return PowCon;
  }

  public void setPowCon(int PowCon) {
    this.PowCon = PowCon;
  }

  public int getPowCoop() {
    return PowCoop;
  }

  public void setPowCoop(int PowCoop) {
    this.PowCoop = PowCoop;
  }

  public int getPowAuPt() {
    return PowAuPt;
  }

  public void setPowAuPt(int PowAuPt) {
    this.PowAuPt = PowAuPt;
  }

  public int getPowPt() {
    return PowPt;
  }

  public void setPowPt(int PowPt) {
    this.PowPt = PowPt;
  }

  public int getPowDoct() {
    return PowDoct;
  }

  public void setPowDoct(int PowDoct) {
    this.PowDoct = PowDoct;
  }

  public int getPowAuth() {
    return PowAuth;
  }

  public void setPowAuth(int PowAuth) {
    this.PowAuth = PowAuth;
  }

  public int getPowOth() {
    return PowOth;
  }

  public void setPowOth(int PowOth) {
    this.PowOth = PowOth;
  }

  public int getPowTot() {
    return PowTot;
  }

  public void setPowTot(int PowTot) {
    this.PowTot = PowTot;
  }

  public int getRcEthic() {
    return RcEthic;
  }

  public void setRcEthic(int RcEthic) {
    this.RcEthic = RcEthic;
  }

  public int getRcRelig() {
    return RcRelig;
  }

  public void setRcRelig(int RcRelig) {
    this.RcRelig = RcRelig;
  }

  public int getRcGain() {
    return RcGain;
  }

  public void setRcGain(int RcGain) {
    this.RcGain = RcGain;
  }

  public int getRcLoss() {
    return RcLoss;
  }

  public void setRcLoss(int RcLoss) {
    this.RcLoss = RcLoss;
  }

  public int getRcEnds() {
    return RcEnds;
  }

  public void setRcEnds(int RcEnds) {
    this.RcEnds = RcEnds;
  }

  public int getRcTot() {
    return RcTot;
  }

  public void setRcTot(int RcTot) {
    this.RcTot = RcTot;
  }

  public int getRspGain() {
    return RspGain;
  }

  public void setRspGain(int RspGain) {
    this.RspGain = RspGain;
  }

  public int getRspLoss() {
    return RspLoss;
  }

  public void setRspLoss(int RspLoss) {
    this.RspLoss = RspLoss;
  }

  public int getRspOth() {
    return RspOth;
  }

  public void setRspOth(int RspOth) {
    this.RspOth = RspOth;
  }

  public int getRspTot() {
    return RspTot;
  }

  public void setRspTot(int RspTot) {
    this.RspTot = RspTot;
  }

  public int getAffGain() {
    return AffGain;
  }

  public void setAffGain(int AffGain) {
    this.AffGain = AffGain;
  }

  public int getAffLoss() {
    return AffLoss;
  }

  public void setAffLoss(int AffLoss) {
    this.AffLoss = AffLoss;
  }

  public int getAffPt() {
    return AffPt;
  }

  public void setAffPt(int AffPt) {
    this.AffPt = AffPt;
  }

  public int getAffOth() {
    return AffOth;
  }

  public void setAffOth(int AffOth) {
    this.AffOth = AffOth;
  }

  public int getAffTot() {
    return AffTot;
  }

  public void setAffTot(int AffTot) {
    this.AffTot = AffTot;
  }

  public int getWltPt() {
    return WltPt;
  }

  public void setWltPt(int WltPt) {
    this.WltPt = WltPt;
  }

  public int getWltTran() {
    return WltTran;
  }

  public void setWltTran(int WltTran) {
    this.WltTran = WltTran;
  }

  public int getWltOth() {
    return WltOth;
  }

  public void setWltOth(int WltOth) {
    this.WltOth = WltOth;
  }

  public int getWltTot() {
    return WltTot;
  }

  public void setWltTot(int WltTot) {
    this.WltTot = WltTot;
  }

  public int getWlbGain() {
    return WlbGain;
  }

  public void setWlbGain(int WlbGain) {
    this.WlbGain = WlbGain;
  }

  public int getWlbLoss() {
    return WlbLoss;
  }

  public void setWlbLoss(int WlbLoss) {
    this.WlbLoss = WlbLoss;
  }

  public int getWlbPhys() {
    return WlbPhys;
  }

  public void setWlbPhys(int WlbPhys) {
    this.WlbPhys = WlbPhys;
  }

  public int getWlbPsyc() {
    return WlbPsyc;
  }

  public void setWlbPsyc(int WlbPsyc) {
    this.WlbPsyc = WlbPsyc;
  }

  public int getWlbPt() {
    return WlbPt;
  }

  public void setWlbPt(int WlbPt) {
    this.WlbPt = WlbPt;
  }

  public int getWlbTot() {
    return WlbTot;
  }

  public void setWlbTot(int WlbTot) {
    this.WlbTot = WlbTot;
  }

  public int getEnlGain() {
    return EnlGain;
  }

  public void setEnlGain(int EnlGain) {
    this.EnlGain = EnlGain;
  }

  public int getEnlLoss() {
    return EnlLoss;
  }

  public void setEnlLoss(int EnlLoss) {
    this.EnlLoss = EnlLoss;
  }

  public int getEnlEnds() {
    return EnlEnds;
  }

  public void setEnlEnds(int EnlEnds) {
    this.EnlEnds = EnlEnds;
  }

  public int getEnlPt() {
    return EnlPt;
  }

  public void setEnlPt(int EnlPt) {
    this.EnlPt = EnlPt;
  }

  public int getEnlOth() {
    return EnlOth;
  }

  public void setEnlOth(int EnlOth) {
    this.EnlOth = EnlOth;
  }

  public int getEnlTot() {
    return EnlTot;
  }

  public void setEnlTot(int EnlTot) {
    this.EnlTot = EnlTot;
  }

  public int getSklAsth() {
    return SklAsth;
  }

  public void setSklAsth(int SklAsth) {
    this.SklAsth = SklAsth;
  }

  public int getSklPt() {
    return SklPt;
  }

  public void setSklPt(int SklPt) {
    this.SklPt = SklPt;
  }

  public int getSklOth() {
    return SklOth;
  }

  public void setSklOth(int SklOth) {
    this.SklOth = SklOth;
  }

  public int getSklTot() {
    return SklTot;
  }

  public void setSklTot(int SklTot) {
    this.SklTot = SklTot;
  }

  public int getTrnGain() {
    return TrnGain;
  }

  public void setTrnGain(int TrnGain) {
    this.TrnGain = TrnGain;
  }

  public int getTrnLoss() {
    return TrnLoss;
  }

  public void setTrnLoss(int TrnLoss) {
    this.TrnLoss = TrnLoss;
  }

  public int getTranLw() {
    return TranLw;
  }

  public void setTranLw(int TranLw) {
    this.TranLw = TranLw;
  }

  public int getMeansLw() {
    return MeansLw;
  }

  public void setMeansLw(int MeansLw) {
    this.MeansLw = MeansLw;
  }

  public int getEndsLw() {
    return EndsLw;
  }

  public void setEndsLw(int EndsLw) {
    this.EndsLw = EndsLw;
  }

  public int getArenaLw() {
    return ArenaLw;
  }

  public void setArenaLw(int ArenaLw) {
    this.ArenaLw = ArenaLw;
  }

  public int getPtLw() {
    return PtLw;
  }

  public void setPtLw(int PtLw) {
    this.PtLw = PtLw;
  }

  public int getNation() {
    return Nation;
  }

  public void setNation(int Nation) {
    this.Nation = Nation;
  }

  public int getAnomie() {
    return Anomie;
  }

  public void setAnomie(int Anomie) {
    this.Anomie = Anomie;
  }

  public int getNegAff() {
    return NegAff;
  }

  public void setNegAff(int NegAff) {
    this.NegAff = NegAff;
  }

  public int getPosAff() {
    return PosAff;
  }

  public void setPosAff(int PosAff) {
    this.PosAff = PosAff;
  }

  public int getSureLw() {
    return SureLw;
  }

  public void setSureLw(int SureLw) {
    this.SureLw = SureLw;
  }

  public int getIf1() {
    return If1;
  }

  public void setIf1(int If1) {
    this.If1 = If1;
  }

  public int getNotLw() {
    return NotLw;
  }

  public void setNotLw(int NotLw) {
    this.NotLw = NotLw;
  }

  public int getTimeSpc() {
    return TimeSpc;
  }

  public void setTimeSpc(int TimeSpc) {
    this.TimeSpc = TimeSpc;
  }

  public int getFormLw() {
    return FormLw;
  }

  public void setFormLw(int FormLw) {
    this.FormLw = FormLw;
  }

  public String getOthtags() {
    return Othtags;
  }

  public void setOthtags(String Othtags) {
    this.Othtags = Othtags;
  }

  public String getDefined() {
    return Defined;
  }

  public void setDefined(String Defined) {
    this.Defined = Defined;
  }

}


